import Link from 'next/link';

export default async function ResetPasswordPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const params = (await searchParams) || {};
  const token = typeof params.token === 'string' ? params.token : '';

  return (
    <main className="mx-auto flex min-h-screen max-w-md items-center px-6">
      <form action="/api/auth/reset-password" method="post" className="glass w-full rounded-[32px] p-8">
        <div className="badge">New password</div>
        <h1 className="mt-5 text-3xl font-bold text-white">Finish password reset</h1>
        <p className="mt-2 text-slate-400">Use the token generated by the recovery flow in demo mode, or wire this to your email provider in production.</p>
        {params.error === 'token_invalid' && <p className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-300">This token is invalid or expired.</p>}
        {params.error === 'invalid_input' && <p className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-300">Use a valid token and a password with at least 8 characters.</p>}
        {params.error === 'rate_limited' && <p className="mt-4 rounded-2xl border border-amber-400/20 bg-amber-400/10 p-4 text-sm text-amber-300">Too many attempts. Try again later.</p>}
        <div className="mt-6 space-y-4">
          <input name="token" defaultValue={token} placeholder="Reset token" className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 font-mono text-white" required />
          <input name="password" type="password" placeholder="New password" className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-white" required />
          <button className="w-full rounded-2xl bg-cyan-400 px-4 py-3 font-semibold text-slate-950">Update password</button>
        </div>
        <div className="mt-6 text-sm text-slate-400">
          Back to <Link className="text-cyan-300" href="/login">sign in</Link>
        </div>
      </form>
    </main>
  );
}
